samrach:
  appName: Student Management
  version: 1.0.0
server:
  error:
    whitelabel:
      enabled: false

spring:
  thymeleaf:
    enabled: true
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/student-management
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

logging:
  level:
    sql: debug